name: Test and Coveralls Parallel

on: 
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test_number:
          - 1
          - 2
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage ${{ matrix.test_number }}
        run: |
          export TEST_NUMBER=${{ matrix.test_number }}
          npm run test:coverage
        env:
          CI: true  # Ensures Jest behaves correctly in CI

      - name: Debug Coverage Output
        run: cat ./coverage-${{ matrix.test_number }}/lcov.info

      - name: Upload coverage to Coveralls (parallel)
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage-${{ matrix.test_number }}/lcov.info
          flag-name: run-${{ join(matrix.*, '-') }}
          parallel: true
          debug: true

  finish:
    needs: test
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Notify Coveralls parallel jobs are finished
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
          carryforward: "run-1,run-2"
